# Generated by Django 5.2.3 on 2025-06-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('initial_deck_json', models.TextField()),
                ('player_hands_json', models.TextField()),
                ('global_desk_json', models.TextField()),
                ('current_player', models.IntegerField(default=1)),
                ('game_started', models.BooleanField(default=False)),
                ('game_over', models.BooleanField(default=False)),
                ('winner_player_num', models.IntegerField(blank=True, null=True)),
                ('cards_map_json', models.TextField()),
                ('player_with_7h', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Badam Satti Game',
                'verbose_name_plural': 'Badam Satti Games',
            },
        ),
    ]
